### ISSUE TITLE
fails to install with meteor add...

### ISSUE THREAD

**Issue by delay** [softwarerero/meteor-accounts-t9n#184]
I am getting this error: 
```
error: No compatible binary build found for this package. Contact the package author and
ask them to publish it for your platform.
```
when adding `meteor add softwarerero:accounts-t9n`.

I am using macOS...

Thanks for any help...

**Comment by delay** [comment]
problem on my end.  I did a meteor reset and it added correctly.

**Comment by softwarerero** [comment]
I could reproduce your problem with Meteor 1.5.2.2, but I don't know what to do about it. Since a few releases whenever I issue `meteor publish` I get the error: 
```
=> Errors while publishing:
While uploading build:
error: Error: ETIMEDOUT
```
I'm not sure if it's related but it seems likely.

As a workaround you can either install an older version like `meteor add softwarerero:accounts-t9n@1.3.11` or (and this is preferred) directly from npm with `npm i -S meteor-accounts-t9n`.

**Comment by softwarerero** [comment]
Please see at #189 which reports the same issue, there is a solution.

**Comment by delay** [comment]
Thanks I will install it as an npm package.
